### ISSUE TITLE
Check if app is hidden with Open at login on Mojave

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#98] opened 2020-09-06 15:28 UTC
This this end up making the cut to 20.5? It’s not working for me (i.e. the app launches at login and is not hidden).

Due 20.5 (6212)
macOS 10.14.6 (18G6020)

_Originally posted by @vitorgalvao in https://github.com/dueapp/Due-macOS/issues/39#issuecomment-687774041_

**Comment by vitorgalvao** [comment] 2020-09-06 15:59
If you end up being unable to reproduce it on Mojave, please let me know which debug steps you’d like me to perform.

**Comment by junjie** [comment] 2020-09-07 07:46
Thanks. I seem to be able to reproduce it on my Catalina now too, though it seems to be working on my virtual machine. We'll look into it

**Comment by vitorgalvao** [comment] 2020-09-15 03:30
I’ve noticed a related regression. Ever since this update, Due does not obey `open` commands such as `-j` (start hidden) or `-g` (do not bring to foreground).

**Comment by honcheng** [comment] 2020-09-16 04:21
@vitorgalvao Thanks. I can confirm that it is a regression caused by a fix for an unrelated issue. 
A fix for this will be out in 20.6, and it will also obey `open` `-j`.

**Closed as completed by honcheng** 2020-09-16 04:21 UTC
Labels: bug
