### ISSUE TITLE
Cell lays out with lots of blank space on first appearance when docked to menu bar icon

### ISSUE THREAD

**Issue by junjie** [dueapp/Due-macOS#123] opened 2020-11-25 07:46 UTC
![CleanShot 2020-11-25 at 15 42 23@2x](https://user-images.githubusercontent.com/524420/100197323-24acab00-2f35-11eb-926a-bbe5015cb99f.png)

Dismissing the window then clicking on the menu bar icon to show the window again fixes the problem.

I noticed also that when not running in menu bar only mode, the app launches momentarily with the blank space laid out before reloading to the proper layout.

**Comment by honcheng** [comment] 2020-12-03 03:47
I cannot reproduce this problem with the steps provided. But I did manage to reproduce it another way, and I suspect the bug is the same. 

Steps: 
1. Launched the app, and resize the window to its minimum width 
2. Dock the app to menu bar 
3. Detached from menu bar 
4. Drag to resize the window 

Expected:
Cell heights should change when window size changes because the text fits the width of the window 

Actual Result:
Labels occupy the width of the resized window, but cell heights did not change, so there are more space below each cells. 

This should be fixed in 20.9

**Comment by honcheng** [comment] 2020-12-03 05:46
Managed to reproduce the problem reported by @junjie using a specific sample data set. Fixed and will be available in 20.9

**Closed as completed by honcheng** 2020-12-03 05:46 UTC
Labels: bug, design
